### ISSUE TITLE
PlatformOI

### ISSUE THREAD

**Issue by ericbaril72** [hugllc/samc21_can#6]
You make reference to platformIO.
How did you manage to use SAMD for the arduino-framework ?

I keep getting : This board doesn't support arduino framework
Any tips would help.  Have done plenty of D21, D51 and E5x including bootloader but platformio is a different beast

**Comment by prices** [comment]
Using the SAMD is well documented in platformio.  I'm sorry, but I don't have the time to help you troubleshoot the issues you are having.

Thanks!

**Comment by ericbaril72** [comment]
In case anyone would try the same...
The samc21_pro board is not supported under the arduino framework.
However,  fortytwo-systems has a board called "one" ... merging the platform.ini with yours gets the job done:

[env:fortytwo_uno]
board = fortytwo_uno
framework = arduino

platform = https://github.com/fortytwosystems/platform-atmelsam.git
platform_packages = 
    framework-arduino-samc-fortytwo @ https://github.com/fortytwosystems/ArduinoCore-samc
    framework-cmsis-microchip       @ https://github.com/fortytwosystems/ArduinoModule-CMSIS-Microchip
    tool-bossac-samc                @ https://github.com/fortytwosystems/BOSSA#pio-windows

lib_deps =  https://github.com/hugllc/samc21_can.git      ;
            https://github.com/fortytwosystems/ArduinoLibrary-CAN
